# .travis.yml
# ...

if: branch = master AND type = push
os: linux
dist: trusty
language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    # android sdk
    - tools
    - platform-tools
    # Android 29 is the current default when creating a new react native app
    - build-tools-29.0.2
    - android-29    
    # additional componenets
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
before_install:
  - nvm install 8.5.0
  - rvm install 2.7.2       #update ruby version for bundler
  - gem install bundler
  - bundle install
  - yes | sdkmanager "platforms;android-29" # You need to automatically accept the terms and conditions of the Android SDK for the specified version
  - chmod +x gradlew                    # gradle permissions
  install:
  - npm install
  - gem install fastlane
script: fastlane android build 
