# .travis.yml
# ...
stage: Deploy Android
if: branch = master AND type = push
language: android
jdk: oraclejdk8
  android:
    components:
      - tools
      - platform-tools
      - android-29    # Android 29 is the current default when creating a new react native app
      - extra-google-m2repository
      - extra-google-google_play_services
    before_install:
      - nvm install 8.5.0
      - gem install bundler
      - bundle install
      - yes | sdkmanager "platforms;android-29" # You need to automatically accept the terms and conditions of the Android SDK for the specified version
    before_script:
      - ./internals/scripts/travis/gitconfig.sh
    install: yarn
    script: fastlane android build